### PR TITLE
seja 1

### PR DESCRIPTION
**Pull request by SvitDolenc**
seja 1

### CODE REVIEW

**Comment by aljazfrancic** [comment]
Looking at files _readings_left_hand/55555-1/4.txt and 5.txt I can see that the labels are wrong (starting with 8?). The labels at the ends of the lines should alternate between hibernation (0) and the gesture denoted in the file name every five seconds, starting with zeros.

**Comment by SvitDolenc** [comment]
popravek seje 1

**Comment by SvitDolenc** [comment]
seja 2

**Comment by SvitDolenc** [comment]
seja 3

**Comment by aljazfrancic** [comment]
Everything looks fine, except your are missing the "0.txt" files, which should contain only hibernation labels (0) at the ends of the lines. You can add these files to your existing sessions, then I'll gladly merge your commit... Hibernation recordings contain various slight movements and motions of the hand that we would prefer to ignore during classification.

I see you also added the optional sign of the horns gesture. Nice!

**Comment by SvitDolenc** [comment]
Dodajanje 0.txt v seje

**Pull request merged**
